<?php

namespace AppBundle\Repository;

/**
 * IndexLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndexLogRepository extends \Doctrine\ORM\EntityRepository
{
}
