<?php

namespace AppBundle\Repository;

/**
 * TestLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestLogRepository extends \Doctrine\ORM\EntityRepository
{
}
